### ISSUE TITLE
Transfer of personal data

### ISSUE THREAD

**Issue by moogion** [JarvisCraft/JarvisCraft#1]
_Сразу же извиняюсь за написание данного вопроса на русском языке._

### Основное

Здравствуй @JarvisCraft, вот решил проявить хоть какую-то активность на GitHub написав логичный вопрос с предложением о переносе персональных данных.

**GitHub Pages** же доступны в подобных репозиториях, да? Ну так вот, предлагаю перенести ваш сайт в отдельную ветку данного репозитория и указать его в роли данных GitHub Pages. 

Причиной этого примитивная логика и желание укротить количество репозиторий (для красоты?).

### Дополнительно

В дальнейшим можно будет загрузить другие данные которые вы захотите, как не странно, к примеру ваш персональный дизайн 😉.

**Comment by JarvisCraft** [comment]
В этом нет никакого смысла:
- `{username}/{username}` пасхалка, единственная задача которой отображать README.md на странице профиля
- Уже [есть](https://github.com/JarvisCraft/JarvisCraft.github.io) репозиторий GitHub Pages, на который итак ссылается https://progrm-jarvis.ru/, а проблемы с количеством репозиториев ныне нет
- Использование разных веток для разных целей - неоднозначная практика, не соответствующая идеологии Git
